# Generated by Django 3.1.7 on 2021-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('poster', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, default='0000-00-00', null=True)),
                ('ratting', models.FloatField(default=0)),
                ('running_time', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('video', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('trailer', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
