# Generated by Django 3.1.7 on 2021-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0002_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('plan_name', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='plan',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='subscription_plan',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
